//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.26 at 02:12:54 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://it.camp.pl/countries/")
package pl.camp.it.countries;
